[providers]
providers = ["node"]

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "true"

[phases.setup]
aptPkgs = ["curl", "build-essential"]

[phases.build]
cmds = [
    "cd backend",
    "npm ci --only=production --no-optional"
]

[phases.start]
cmd = "cd backend && npm start"

[build]
excludePaths = ["frontend/**", "node_modules", ".git", "*.md", ".env*"] 