[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
buildCommand = "echo 'Using Dockerfile build'"
watchPatterns = ["backend/**"]

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

# 确保自动部署配置
[environments.production]
variables = { NODE_ENV = "production", NPM_CONFIG_PRODUCTION = "true" } 