[build]
builder = "nixpacks"
nixpacksConfigPath = "backend"

[deploy]
startCommand = "npm start"
workingDirectory = "backend"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[environments.production]
variables = { NODE_ENV = "production" } 