services:
  - type: web
    name: work-assistant-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: work-assistant-db
          property: connectionString

databases:
  - name: work-assistant-db
    plan: free 